/***********************************************************************/
/*                                                                     */
/*  FILE        :h8s_arduino.c                                         */
/*  DATE        :Wed, Jul 14, 2021                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8S/2215                                              */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
#define ARDUINO_MAIN
#include "Arduino.h"                  
#include "iodefine.h"
#include "UARTClass.h"
UARTClass Serial(6,8);

#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
	(*--p) ();

    }
}
#endif 

int main(void)
{
     setup();
    while(1)
    {
        loop();
		if (serialEventRun) serialEventRun();
    }
  return 0;
}


