/***********************************************************************/
/*                                                                     */
/*  FILE        :h8s_arduino.c                                         */
/*  DATE        :Wed, Jul 14, 2021                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8S/2215                                              */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
#define ARDUINO_MAIN
#include "Arduino.h"                 
#include "ioh82623.h"
#include "UartClass.h"

UARTClass Serial;

int main(void)
{
    setup();
    while(1)
    {
        loop();
        Serial.rx_event();
    }

    return 0;

}


