/***********************************************************************/
/*                                                                     */
/*  FILE        :hwinit.c                                              */
/*  DATE        :Wed, Jul 14, 2021                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :H8S/2215                                              */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
                  



#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void hw_initialise(void);
#ifdef __cplusplus
}
#endif


void hw_initialise(void)
{
/*
  TPU.TSTR.BYTE = 0;
  TPU.TSTR.BIT.CST2 = 1;
  TPU.TSTR.BIT.CST1 = 1;
  TPU.TSTR.BIT.CST0 = 1;
  TPU.TSYR.BYTE = 0;
  TPU.TSYR.BIT.SYNC2 = 1;
  TPU.TSYR.BIT.SYNC1 = 1;
  TPU.TSYR.BIT.SYNC0 = 1;
*/
}
