/***********************************************************************/
/*                                                                     */
/*  FILE        :inthandler.h                                          */
/*  DATE        :Wed, Jul 14, 2021                                     */
/*  DESCRIPTION :Interrupt Handler Declarations                        */
/*  CPU TYPE    :H8S/2215                                              */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
                        





#ifndef INTHANDLER_H
#define INTHANDLER_H

//  vector 1 Manual Reset
void INT_Manual_Reset(void)  __attribute__ ((interrupt_handler));
// vector 2 Reserved

// vector 3 Reserved

// vector 4 Reserved

// vector 5 TRACE
void INT_TRACE(void)  __attribute__ ((interrupt_handler));
// vector 6 Direct Transition
void INT_Direct_Transition(void)  __attribute__ ((interrupt_handler));
// vector 7 NMI
void INT_NMI(void)  __attribute__ ((interrupt_handler));
// vector 8 trap #0
void INT_TRAP0(void)  __attribute__ ((interrupt_handler));
// vector 9 trap #1
void INT_TRAP1(void)  __attribute__ ((interrupt_handler));
// vector 10 trap #2
void INT_TRAP2(void)  __attribute__ ((interrupt_handler));
// vector 11 trap #3
void INT_TRAP3(void)  __attribute__ ((interrupt_handler));
// vector 12 Reserved

// vector 13 Reserved

// vector 14 Reserved

// vector 15 Reserved

// vector 16 External trap IRQ0
void INT_IRQ0(void)  __attribute__ ((interrupt_handler));
// vector 17 External trap IRQ1
void INT_IRQ1(void)  __attribute__ ((interrupt_handler));
// vector 18 External trap IRQ2
void INT_IRQ2(void)  __attribute__ ((interrupt_handler));
// vector 19 External trap IRQ3
void INT_IRQ3(void)  __attribute__ ((interrupt_handler));
// vector 20 External trap IRQ4
void INT_IRQ4(void)  __attribute__ ((interrupt_handler));
// vector 21 External trap IRQ5
void INT_IRQ5(void)  __attribute__ ((interrupt_handler));
// vector 22 External trap IRQ6
void INT_IRQ6(void)  __attribute__ ((interrupt_handler));
// vector 23 External trap IRQ7
void INT_IRQ7(void)  __attribute__ ((interrupt_handler));
// vector 24 SWDTEND DTC
void INT_SWDTEND_DTC(void)  __attribute__ ((interrupt_handler));
// vector 25 WOVI
void INT_WOVI(void)  __attribute__ ((interrupt_handler));
// vector 26 Reserved

// vector 27 Reserved

// vector 28 ADI
void INT_ADI(void)  __attribute__ ((interrupt_handler));
// vector 29 Reserved

// vector 30 Reserved

// vector 31 Reserved

// vector 32 TGI0A TPU0
void INT_TGI0A_TPU0(void)  __attribute__ ((interrupt_handler));
// vector 33 TGI0B TPU0
void INT_TGI0B_TPU0(void)  __attribute__ ((interrupt_handler));
// vector 34 TGI0C TPU0
void INT_TGI0C_TPU0(void)  __attribute__ ((interrupt_handler));
// vector 35 TGI0D TPU0
void INT_TGI0D_TPU0(void)  __attribute__ ((interrupt_handler));
// vector 36 TCI0V TPU0
void INT_TCI0V_TPU0(void)  __attribute__ ((interrupt_handler));
// vector 37 Reserved

// vector 38 Reserved

// vector 39 Reserved

// vector 40 TGI1A TPU1
void INT_TGI1A_TPU1(void)  __attribute__ ((interrupt_handler));
// vector 41 TGI1B TPU1
void INT_TGI1B_TPU1(void)  __attribute__ ((interrupt_handler));
// vector 42 TCI1V TPU1
void INT_TCI1V_TPU1(void)  __attribute__ ((interrupt_handler));
// vector 43 TCI1U TPU1
void INT_TCI1U_TPU1(void)  __attribute__ ((interrupt_handler));
// vector 44 TGI2A TPU2
void INT_TGI2A_TPU2(void)  __attribute__ ((interrupt_handler));
// vector 45 TGI2B TPU2
void INT_TGI2B_TPU2(void)  __attribute__ ((interrupt_handler));
// vector 46 TCI2V TPU2
void INT_TCI2V_TPU2(void)  __attribute__ ((interrupt_handler));
// vector 47 TCI2U TPU2
void INT_TCI2U_TPU2(void)  __attribute__ ((interrupt_handler));
// vector 48 Reserved

// vector 49 Reserved

// vector 50 Reserved

// vector 51 Reserved

// vector 52 Reserved

// vector 53 Reserved

// vector 54 Reserved

// vector 55 Reserved

// vector 56 Reserved

// vector 57 Reserved

// vector 58 Reserved

// vector 59 Reserved

// vector 60 Reserved

// vector 61 Reserved

// vector 62 Reserved

// vector 63 Reserved

// vector 64 CMIA0 8Bit0
void INT_CMIA0_8BIT0(void)  __attribute__ ((interrupt_handler));
// vector 65 CMIB0 8Bit0
void INT_CMIB0_8BIT0(void)  __attribute__ ((interrupt_handler));
// vector 66 OVI0 8Bit0
void INT_OVI0_8BIT0(void)  __attribute__ ((interrupt_handler));
// vector 67 Reserved

// vector 68 CMIA1 8Bit1
void INT_CMIA1_8BIT1(void)  __attribute__ ((interrupt_handler));
// vector 69 CMIB1 8Bit1
void INT_CMIB1_8BIT1(void)  __attribute__ ((interrupt_handler));
// vector 70 OVI1 8Bit1
void INT_OVI1_8BIT1(void)  __attribute__ ((interrupt_handler));
// vector 71 Reserved

// vector 72 DEND0A DMAC
void INT_DEND0A_DMAC(void)  __attribute__ ((interrupt_handler));
// vector 73 DEND0B DMAC
void INT_DEND0B_DMAC(void)  __attribute__ ((interrupt_handler));
// vector 74 DEND1A DMAC
void INT_DEND1A_DMAC(void)  __attribute__ ((interrupt_handler));
// vector 75 DEND1B DMAC
void INT_DEND1B_DMAC(void)  __attribute__ ((interrupt_handler));
// vector 76 Reserved

// vector 77 Reserved

// vector 78 Reserved

// vector 79 Reserved

// vector 80 ERI0 SCI0
void INT_ERI0_SCI0(void)  __attribute__ ((interrupt_handler));
// vector 81 RXI0 SCI0
void INT_RXI0_SCI0(void)  __attribute__ ((interrupt_handler));
// vector 82 TXI0 SCI0
void INT_TXI0_SCI0(void)  __attribute__ ((interrupt_handler));
// vector 83 TEI0 SCI0
void INT_TEI0_SCI0(void)  __attribute__ ((interrupt_handler));
// vector 84 ERI1 SCI1
void INT_ERI1_SCI1(void)  __attribute__ ((interrupt_handler));
// vector 85 RXI1 SCI1
void INT_RXI1_SCI1(void)  __attribute__ ((interrupt_handler));
// vector 86 TXI1 SCI1
void INT_TXI1_SCI1(void)  __attribute__ ((interrupt_handler));
// vector 87 TEI1 SCI1
void INT_TEI1_SCI1(void)  __attribute__ ((interrupt_handler));
// vector 88 ERI2 SCI2
void INT_ERI2_SCI2(void)  __attribute__ ((interrupt_handler));
// vector 89 RXI2 SCI2
void INT_RXI2_SCI2(void)  __attribute__ ((interrupt_handler));
// vector 90 TXI2 SCI2
void INT_TXI2_SCI2(void)  __attribute__ ((interrupt_handler));
// vector 91 TEI2 SCI2
void INT_TEI2_SCI2(void)  __attribute__ ((interrupt_handler));
// vector 92 Reserved

// vector 93 Reserved

// vector 94 Reserved

// vector 95 Reserved

// vector 96 Reserved

// vector 97 Reserved

// vector 98 Reserved

// vector 99 Reserved

// vector 100 Reserved

// vector 101 Reserved

// vector 102 Reserved

// vector 103 Reserved

// vector 104 EXIRQ0 USB
void INT_EXIRQ0_USB(void)  __attribute__ ((interrupt_handler));
// vector 105 EXIRQ1 USB
void INT_EXIRQ1_USB(void)  __attribute__ ((interrupt_handler));
// vector 106 Reserved

// vector 107 Reserved

// vector 108 Reserved

// vector 109 Reserved

// vector 110 Reserved

// vector 111 Reserved

// vector 112 Reserved

// vector 113 Reserved

// vector 114 Reserved

// vector 115 Reserved

// vector 116 Reserved

// vector 117 Reserved

// vector 118 Reserved

// vector 119 Reserved

// vector 120 Reserved

// vector 121 Reserved

// vector 122 Reserved

// vector 123 Reserved

// vector 124 Reserved

// vector 125 Reserved

// vector 126 Reserved

// vector 127 Reserved

#endif

