/***********************************************************************/
/*                                                                     */
/*  FILE        :vects.c                                               */
/*  DATE        :Wed, Jul 14, 2021                                     */
/*  DESCRIPTION :Vector Table                                          */
/*  CPU TYPE    :H8S/2215                                              */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
                        



#include "inthandler.h"
typedef  void (*fp) (void);
extern void start(void);
extern void stack (void);

#define VECT_SECT          __attribute__ ((section (".vects")))
const fp HardwareVectors[] VECT_SECT  = {
//;<<VECTOR DATA START (POWER ON RESET)>>
//;0 Power On Reset PC
start,
//;<<VECTOR DATA END (POWER ON RESET)>>
//vector 1 manual reset
//;<<VECTOR DATA START (MANUAL RESET)>>
//;2 Manual Reset PC
INT_Manual_Reset,
//;<<VECTOR DATA END (MANUAL RESET)>>
// vector 2 Reserved
(fp)0,
// vector 3 Reserved
(fp)0,
// vector 4 Reserved
(fp)0,
// vector 5 TRACE
 INT_TRACE,
// vector 6 Direct Transition
 INT_Direct_Transition,
// vector 7 NMI
 INT_NMI,
// vector 8 trap #0
 INT_TRAP0,
// vector 9 trap #1
 INT_TRAP1,
// vector 10 trap #2
 INT_TRAP2,
// vector 11 trap #3
 INT_TRAP3,
// vector 12 Reserved
(fp)0,
// vector 13 Reserved
(fp)0,
// vector 14 Reserved
(fp)0,
// vector 15 Reserved
(fp)0,
// vector 16 External trap IRQ0
 INT_IRQ0,
// vector 17 External trap IRQ1
 INT_IRQ1,
// vector 18 External trap IRQ2
 INT_IRQ2,
// vector 19 External trap IRQ3
 INT_IRQ3,
// vector 20 External trap IRQ4
 INT_IRQ4,
// vector 21 External trap IRQ5
 INT_IRQ5,
// vector 22 External trap IRQ6
 INT_IRQ6,
// vector 23 External trap IRQ7
 INT_IRQ7,
// vector 24 SWDTEND DTC
 INT_SWDTEND_DTC,
// vector 25 WOVI
 INT_WOVI,
// vector 26 Reserved
(fp)0,
// vector 27 Reserved
(fp)0,
// vector 28 ADI
 INT_ADI,
// vector 29 Reserved
(fp)0,
// vector 30 Reserved
(fp)0,
// vector 31 Reserved
(fp)0,
// vector 32 TGI0A TPU0
 INT_TGI0A_TPU0,
// vector 33 TGI0B TPU0
 INT_TGI0B_TPU0,
// vector 34 TGI0C TPU0
 INT_TGI0C_TPU0,
// vector 35 TGI0D TPU0
 INT_TGI0D_TPU0,
// vector 36 TCI0V TPU0
 INT_TCI0V_TPU0,
// vector 37 Reserved
(fp)0,
// vector 38 Reserved
(fp)0,
// vector 39 Reserved
(fp)0,
// vector 40 TGI1A TPU1
 INT_TGI1A_TPU1,
// vector 41 TGI1B TPU1
 INT_TGI1B_TPU1,
// vector 42 TCI1V TPU1
 INT_TCI1V_TPU1,
// vector 43 TCI1U TPU1
 INT_TCI1U_TPU1,
// vector 44 TGI2A TPU2
 INT_TGI2A_TPU2,
// vector 45 TGI2B TPU2
 INT_TGI2B_TPU2,
// vector 46 TCI2V TPU2
 INT_TCI2V_TPU2,
// vector 47 TCI2U TPU2
 INT_TCI2U_TPU2,
// vector 48 Reserved
(fp)0,
// vector 49 Reserved
(fp)0,
// vector 50 Reserved
(fp)0,
// vector 51 Reserved
(fp)0,
// vector 52 Reserved
(fp)0,
// vector 53 Reserved
(fp)0,
// vector 54 Reserved
(fp)0,
// vector 55 Reserved
(fp)0,
// vector 56 Reserved
(fp)0,
// vector 57 Reserved
(fp)0,
// vector 58 Reserved
(fp)0,
// vector 59 Reserved
(fp)0,
// vector 60 Reserved
(fp)0,
// vector 61 Reserved
(fp)0,
// vector 62 Reserved
(fp)0,
// vector 63 Reserved
(fp)0,
// vector 64 CMIA0 8Bit0
 INT_CMIA0_8BIT0,
// vector 65 CMIB0 8Bit0
 INT_CMIB0_8BIT0,
// vector 66 OVI0 8Bit0
 INT_OVI0_8BIT0,
// vector 67 Reserved
(fp)0,
// vector 68 CMIA1 8Bit1
 INT_CMIA1_8BIT1,
// vector 69 CMIB1 8Bit1
 INT_CMIB1_8BIT1,
// vector 70 OVI1 8Bit1
 INT_OVI1_8BIT1,
// vector 71 Reserved
(fp)0,
// vector 72 DEND0A DMAC
 INT_DEND0A_DMAC,
// vector 73 DEND0B DMAC
 INT_DEND0B_DMAC,
// vector 74 DEND1A DMAC
 INT_DEND1A_DMAC,
// vector 75 DEND1B DMAC
 INT_DEND1B_DMAC,
// vector 76 Reserved
(fp)0,
// vector 77 Reserved
(fp)0,
// vector 78 Reserved
(fp)0,
// vector 79 Reserved
(fp)0,
// vector 80 ERI0 SCI0
 INT_ERI0_SCI0,
// vector 81 RXI0 SCI0
 INT_RXI0_SCI0,
// vector 82 TXI0 SCI0
 INT_TXI0_SCI0,
// vector 83 TEI0 SCI0
 INT_TEI0_SCI0,
// vector 84 ERI1 SCI1
 INT_ERI1_SCI1,
// vector 85 RXI1 SCI1
 INT_RXI1_SCI1,
// vector 86 TXI1 SCI1
 INT_TXI1_SCI1,
// vector 87 TEI1 SCI1
 INT_TEI1_SCI1,
// vector 88 ERI2 SCI2
 INT_ERI2_SCI2,
// vector 89 RXI2 SCI2
 INT_RXI2_SCI2,
// vector 90 TXI2 SCI2
 INT_TXI2_SCI2,
// vector 91 TEI2 SCI2
 INT_TEI2_SCI2,
// vector 92 Reserved
(fp)0,
// vector 93 Reserved
(fp)0,
// vector 94 Reserved
(fp)0,
// vector 95 Reserved
(fp)0,
// vector 96 Reserved
(fp)0,
// vector 97 Reserved
(fp)0,
// vector 98 Reserved
(fp)0,
// vector 99 Reserved
(fp)0,
// vector 100 Reserved
(fp)0,
// vector 101 Reserved
(fp)0,
// vector 102 Reserved
(fp)0,
// vector 103 Reserved
(fp)0,
// vector 104 EXIRQ0 USB
 INT_EXIRQ0_USB,
// vector 105 EXIRQ1 USB
 INT_EXIRQ1_USB,
// vector 106 Reserved
(fp)0,
// vector 107 Reserved
(fp)0,
// vector 108 Reserved
(fp)0,
// vector 109 Reserved
(fp)0,
// vector 110 Reserved
(fp)0,
// vector 111 Reserved
(fp)0,
// vector 112 Reserved
(fp)0,
// vector 113 Reserved
(fp)0,
// vector 114 Reserved
(fp)0,
// vector 115 Reserved
(fp)0,
// vector 116 Reserved
(fp)0,
// vector 117 Reserved
(fp)0,
// vector 118 Reserved
(fp)0,
// vector 119 Reserved
(fp)0,
// vector 120 Reserved
(fp)0,
// vector 121 Reserved
(fp)0,
// vector 122 Reserved
(fp)0,
// vector 123 Reserved
(fp)0,
// vector 124 Reserved
(fp)0,
// vector 125 Reserved
(fp)0,
// vector 126 Reserved
(fp)0,
// vector 127 Reserved
(fp)0,
};
